#!/usr/bin/env python3
"""Losslessly compress the embedded GSPB for the immutable Recovery slot."""
from pathlib import Path
import argparse
import zlib

try:
    import zopfli.zlib
except ImportError as error:
    raise SystemExit("Recovery bundle compression requires zopfli: install "
                     "firmware/recovery/tools/requirements.txt with the build Python") from error


def pack(source, output):
    raw = Path(source).read_bytes()
    # Font bitmaps and scene records benefit from different Deflate match
    # heuristics. Keep the default stream as a candidate so this optimization
    # never grows the bundle. All candidates use the same zlib format accepted
    # by the device's ROM tinfl decoder; no new runtime codec is required.
    # Spend a few seconds on the host to save Flash without changing the ROM
    # decoder or a single decompressed scene/font byte.
    candidates = [zlib.compress(raw, 9),
                  zopfli.zlib.compress(raw, numiterations=200)]
    for memory in (6, 7, 8, 9):
        for strategy in (zlib.Z_DEFAULT_STRATEGY, zlib.Z_FILTERED):
            encoder = zlib.compressobj(9, zlib.DEFLATED, 15, memory, strategy)
            candidates.append(encoder.compress(raw) + encoder.flush())
    packed = min(candidates, key=len)
    assert zlib.decompress(packed) == raw
    lines = ["// Generated by pack_vibe_bundle.py; do not edit.",
             "#include <stddef.h>", "#include <stdint.h>",
             "const size_t vibe_bundle_size = %d;" % len(raw),
             "const size_t vibe_bundle_compressed_size = %d;" % len(packed),
             "const uint8_t vibe_bundle_compressed[] = {"]
    lines.extend("    " + ",".join("0x%02x" % b for b in packed[i:i + 24]) + ","
                 for i in range(0, len(packed), 24))
    lines.append("};\n")
    Path(output).write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source")
    parser.add_argument("output")
    args = parser.parse_args()
    pack(args.source, args.output)
